swagger: "2.0"
info:
  title: "__apiTitle__"
  description: "__apiDescription__"
  version: "__apiVersion__"
host: "__hostName__"
basePath: "__basePath__"
consumes: 
  - "application/json"
produces: 
  - "application/json"
schemes: 
  - "http"
  - "https"
